### ISSUE TITLE
Error in msk create command

### ISSUE THREAD

**Issue by YogeshSingla** [MycroftAI/mycroft-skills-kit#1]
After installing with `pip3 install msk` I ran the command `msk create`. This error occurred (attached file). Can you please tell why this is happening? 
[error.txt](https://github.com/MycroftAI/mycroft-skills-kit/files/2061098/error.txt)

**Comment by MatthewScholefield** [comment]
It looks like you are running `msk` using Windows. I've just added that at this time, Linux is the only OS that has been tested. However, there's a *chance* that it will work after adding customizing the default directories via command line arguments. Try running all commands like this:
```
msk -c skills-repo -s skills-dir create
```
which will tell it to use clone the skills repo in the current directory as `skills-repo/` and make the skills directory (where to put the skill) in the current directory as `skills-dir/`.

**Comment by YogeshSingla** [comment]
It looks to me that `msk` is not taking any flags. 
```
$ msk -c switch-control -s /opt/mycroft/skills/ create
usage: msk [-h] {upgrade,upload,create,create-test} ...
msk: error: argument action: invalid choice: 'switch-control' (choose from 'upgrade', 'upload', 'create', 'create-test')
```

I have switched to linux and its working fine after adding `msk` to PATH.

**Comment by MatthewScholefield** [comment]
Make sure to update to the latest msk before trying to run it with command line options. I only added in the last version or two.

**Comment by MatthewScholefield** [comment]
Closing since the initial issue has been addressed, but if you ever feel like trying it on windows again, feel free to comment on this thread.

**Comment by deicool** [comment]
Trying on Windows...I am a newbie too. How do I proceed?

**Comment by krisgesling** [comment]
Hi @deicool, we don't support Windows at the moment. 

I'd recommend running Linux in a VM or running Picroft on a Raspberry Pi if you have one handy.
