### ISSUE TITLE
can not update skill not yet approved

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-skills-kit#12]
changes were requested to a skill i submitted (laugh and parrot)

however if i try to run msk upgrade i get an error

```
(.venv) user@JAntIx:~/PycharmProjects/core
$ msk --skills-dir "/home/user/PycharmProjects" upgrade "/home/user/PycharmProjects/skill-parrot"
NotUploaded: Skill at folder not uploaded to store: /home/user/PycharmProjects/skill-parrot

```

there should be an option to update PRs, maybe "msk update"

as a side note, update could be an alias to upgrade instead

**Comment by MatthewScholefield** [comment]
Definitely onboard with the update alias. It will update an existing PR if you rerun `msk upload` (assuming you are uploading for the first time). However, I do think it's worth having `msk upgrade` check if there's a PR to add that skill and if so update that. That way you don't have to reenter the description and all that.

**Comment by krisgesling** [comment]
I believe this has been resolved. Please reopen if I'm mistaken.
