### ISSUE TITLE
Automatic testing fails on Adapt intents

### ISSUE THREAD

**Issue by lb803** [MycroftAI/mycroft-skills-kit#18]
Hello!
I am creating tests on a [little skill](https://github.com/lb803/list-manager-skill) I am writing, which doesn't have padatious intents files, but intents are generated via IntentBuilder.

As I fire up: 'msk create-test /opt/mycroft/skills/list-manager-skill/' I get:

> MskException: No existing intents found. Please create some first

Is this expected? 
Or, am I missing something somewhere?
Thanks very much!

Developing on picroft 19.02.2, msk v. 0.3.12.

**Comment by MatthewScholefield** [comment]
Fixed by #19.
