### ISSUE TITLE
Github password can't handle " (double quote)

### ISSUE THREAD

**Issue by timo-a** [MycroftAI/mycroft-skills-kit#29]
When creating a new skill the wizard asks if user wants to create a github repo for it.  If user says `y` the wizard asks for the credentials. While Github can handle passwords containing `"`, mycroft cannot.

I'm using v19.8.3 (commit c2904335f... 2019-11-14)

How to reproduce:

1. have a github password 123"456
2. `cd mycroft-core/bin; ./mycroft-msk` always say `y`
3. wizard asks for github credentials, input user name + password
Wizard says:

       File "/tmp/tmp032xdx22", line 4
         "123"456"
              ^
       SyntaxError: invalid syntax
       error: unable to read askpass response from '/tmp/tmp032xdx22'

Escaping the double quote works: `123\"456` but skill creators can't be expected to know this.

At the very least: Tell the user that they have to escape double quotes in the password and how.
Ideally, fix it so user can just input their password as on github.

**Comment by ChanceNCounter** [comment]
I doubt it's this simple, but [this](https://github.com/ChanceNCounter/mycroft-skills-kit/tree/encode-password) branch might fix it, @timo-a. I couldn't repro, though, so you'd have to check.

Nothing fancy, just encoding the password for good measure. Seems to work for my password...

**Comment by ChanceNCounter** [comment]
oh, heh, @MatthewScholefield beat me to it

**Comment by MatthewScholefield** [comment]
@ChanceNCounter Haha, same thing always happens to me. Would either of you be able to test the branch? I wrote it on my phone so no idea if it works xD

**Comment by timo-a** [comment]
I can confirm that it works with branch `bugfix/issue-29`!

**Comment by forslund** [comment]
Merged the fix, will create a release and include in next mycroft-release
