### ISSUE TITLE
Default icon and color if nothing is entered

### ISSUE THREAD

**Issue by andlo** [MycroftAI/mycroft-skills-kit#38]
As msk also is use just to make a quick test/demo skill it should be easy to enter the questions duing msk create.
But as it is now icon and color needs to be entered. Would it be an idea to default to a icon and color if user dont enter an icon ad color ?

The code dooing this are a bit complicated for me as I dont understand lambda 

```
icon = Lazy(lambda s: ask_input(
        'Go to Font Awesome ({blue}fontawesome.com/cheatsheet{reset}) and choose an icon.'
        '\nEnter the name of the icon:'.format(blue=Fore.BLUE + Style.BRIGHT, reset=Style.RESET_ALL),
        validator=lambda x:
        requests.get("https://raw.githack.com/FortAwesome/Font-Awesome/"
                     "master/svgs/solid/{x}.svg".format(x=x)).ok,
        on_fail="\n\n{red}Error: The name was not found. Make sure you spelled the icon name right,"
                " and try again.{reset}\n".format(red=Fore.RED + Style.BRIGHT, reset=Style.RESET_ALL)))
```

**Comment by krisgesling** [comment]
Yeah I hit this pretty regularly myself. Sane defaults on an empty submission sounds great. 

I also wonder if we should refactor all the Lambda's so it's easier for people to read and contribute.

**Comment by forslund** [comment]
+1 on the lambdas!

**Comment by forslund** [comment]
And also +1 for the sane defaults!

Robot head and mycroft blue? or randomize it maybe ;)

**Comment by andlo** [comment]
I would say Robot head and mycroft blue as defaults. 

And removing lambda sounds fantastic to me as i defently dont understand what is going on when lambda is used.

But if I can rewrite the icon and color part I can rewrite using somethig I understands. I am willing to try to do that.

**Comment by krisgesling** [comment]
The current question format of:
```Python
name = ask_input(
    'Enter a short unique skill name (ie. "siren alarm" or "pizza orderer"):',
    lambda x: re.match(r'^[a-zA-Z \-]+$', x), 'Please use only letter and spaces.'
).strip(' -').lower().replace(' ', '-')
```
Is essentially equal to:
```Python
question = 'Enter a short unique skill name (ie. "siren alarm" or "pizza orderer"):'
error_msg = 'Please use only letter and spaces.'
def validator(user_input):
    return re.match(r'^[a-zA-Z \-]+$', user_input)
def formatter(user_input):
    return user_input.strip(' -').lower().replace(' ', '-')

user_input = ask_input(question, validator, error_msg)
name = formatter(user_input)
```

Would this expanded version make it more readable and provide a (mostly) consistent format for each question? 

I'm presuming it won't work for all cases, but I haven't really looked.

**Comment by andlo** [comment]
It ooks more readable for me. But the hole create process isnt. It is difficult to se hvat is going on. But I managed to figure out most of it, but it isnt easyly read.
