### ISSUE TITLE
Please distribute license

### ISSUE THREAD

**Issue by scarabeusiv** [MycroftAI/mycroft-skills-kit#4]
Packages on pypi does not contain license file shipped within the tarball. Could you please tweak your manifest to include the file?

**Comment by LyesSaadi** [comment]
Any update on this?

**Comment by forslund** [comment]
I could probably add this, what is the best way of doing it? Many of our other packages use the data_files section to include the license, this makes it look a bit weird and out of place setting the licenses in a folder in the root of the venv or wherever sys.prefix is pointing.

What is best practice for this?

**Comment by scarabeusiv** [comment]
Just add Manifest.in and list all extra files that should be created when you do python setup.py sdist or something along the way that gets later updated to pypi.

Or if you switch to setup.cfg you can use the line to specify there https://packaging.python.org/guides/using-manifest-in/

**Comment by forslund** [comment]
I mean, where would you expect to find it in the package after installation? Or is it that it should exist in the tar.gz on pypi?

**Comment by scarabeusiv** [comment]
It is needed with the source distribution, end-user deploy is handled by the linux distributions and others as needed, you don't really need to figure way to place it somewhere on the install.

**Comment by forslund** [comment]
Gotcha, sorry for being dense. Will PR tonight
