### ISSUE TITLE
Error on initial usage of MSK

### ISSUE THREAD

**Issue by FroogalTheDragon** [MycroftAI/mycroft-skills-kit#59]
**Describe the bug**
I installed the program using `pip3 install msk`

I try to run the program using `msk create`

I get the output:
```
Traceback (most recent call last):
  File "/home/codecanna/.local/bin/msk", line 8, in <module>
    sys.exit(main())
  File "/home/codecanna/.local/lib/python3.9/site-packages/msk/__main__.py", line 57, in main
    skills_dir=args.skills_dir, repo=SkillRepo(url=args.repo_url, 
TypeError: __init__() got an unexpected keyword argument 'path'
```

**To Reproduce**
Run `msk create` and I get that error, no guarantee that you will get this same error.

**Expected behavior**
It should prompt for info about the skill, then create the base skill.

**Log files**
bus.log:
My-croft itself works great, the only issue I'm having is with `msk`.

**Environment (please complete the following information):**
Pop!_OS (Ubuntu 21.04)
Python 3.9.5

**Additional context**
I installed the program using the instructions and tried running it a normal,
`msk create`.

I get the above error, I haven't found much online about this problem.

**Comment by forslund** [comment]
Looks like msk hasn't been updated to the 0.9 version range of msm. (0.9 hasn't quite been adopted in the mycroft ecosystem yet). I propose a quick version lock in #60 until 0.9 of msm starts getting used

**Comment by PureTryOut** [comment]
This is fixed in https://github.com/MycroftAI/mycroft-skills-kit/pull/63

**Comment by forslund** [comment]
As this has been both temporarily and permanently fixed I'll close the issue. feel free to reopen the issue if the problem persists.
