### ISSUE TITLE
Support XDG compatible paths

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-skills-kit#62]
**Is your feature request related to a problem? Please describe.**
Mycroft is moving to be XDG compatible. The PR to move Skills is here: https://github.com/MycroftAI/mycroft-core/pull/2803

Doing this would require an update for MSK to use the new XDG paths for at least:
- Skill creation
- Test creation
- ? something else ?

**Describe the solution you'd like**
Use XDG file paths consistent with https://github.com/MycroftAI/mycroft-core/pull/2803

**Comment by PureTryOut** [comment]
From what I can see `msk create-test` requires the user to specify the path to the skills, which means this needs no adaption for the XDG Base Directory specification no? The user just needs to provide the correct path themselves.

`msk create` has been changed in #63.
