### ISSUE TITLE
Template flaw - Copyright statement in seed MIT.txt license file

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/mycroft-skills-kit#64]
**Describe the bug**
mycroft-skills-kit/msk/licenses/MIT.txt contains attribution "Copyright (C) 2012 Yoshimasa Niwa". Should be a generic/template-prompt or perhaps some kind of neutral entity.

**To Reproduce**
1. mycroft-msk create
2. select MIT license
3. view header of LICENSE.txt to see incorrect, but specific copyright statement

**Expected behavior**
LICENSE.txt should be created with neutral or correct creating-user copyright statement

**Environment (please complete the following information):**
 - Device type: Mark 2
 - Mycroft-core version: 21.02

**Comment by forslund** [comment]
Nice catch, I first read it as the license copyright like in the GPL but you're right that it shouldn't be there.
